name: Checks
on: push
jobs:
  check:
    name: Run checks (linting, unit tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local # path depends on the OS
          key: cache-poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - name: Load cached dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: .venv
          key: poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: poetry install
      - name: Lint
        run: |
          poetry run flake8
      - name: Type check
        run: |
          poetry run mypy
      - name: Run tests
        run: |
          poetry run pytest
